spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:local_db}
spring.datasource.username=${POSTGRES_USER:local_user}
spring.datasource.password=${POSTGRES_PASSWORD:local_garch_db}