spring.application.name=GarchApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/garch_database
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=garch